apiVersion: v1
kind: Service
metadata:
  name: udacity-cloudDevops-capstone-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: udacity-cloudDevops-capstone
  ports:
    - port: 80
      targetPort: 8000